import { NextRequest, NextResponse } from "next/server";
import { getChatGPTUser } from "@/app/chatgpt-auth";
import { getDb } from "@/db";
import { products } from "@/db/schema";
import { and, desc, eq } from "drizzle-orm";
import { z } from "zod";

const productSchema=z.object({id:z.string().optional(),name:z.string().trim().min(1),sku:z.string().trim().min(1),category:z.string().min(1),description:z.string().min(1),price:z.number().positive(),moq:z.number().int().positive(),increment:z.number().int().positive(),dialColour:z.string(),strapMaterial:z.string(),variants:z.array(z.string()).min(1),stockStatus:z.enum(["In Stock","Out of Stock"]),featured:z.boolean(),newArrival:z.boolean(),status:z.enum(["draft","published"]),archived:z.boolean().default(false),coverImage:z.string().optional().nullable(),images:z.array(z.string()).optional()});
const serialize=(p:typeof products.$inferSelect)=>({...p,variants:JSON.parse(p.variants),images:JSON.parse(p.images),coverImage:p.coverImage||undefined});
export async function GET(req:NextRequest){try{const admin=req.nextUrl.searchParams.get("admin")==="1";if(admin&&!await getChatGPTUser())return NextResponse.json({error:"Unauthorized"},{status:401});const rows=admin?await getDb().select().from(products).orderBy(desc(products.updatedAt)):await getDb().select().from(products).where(and(eq(products.status,"published"),eq(products.archived,false))).orderBy(desc(products.updatedAt));return NextResponse.json(rows.map(serialize))}catch{return NextResponse.json([], {status:200})}}
export async function POST(req:NextRequest){if(!await getChatGPTUser())return NextResponse.json({error:"Unauthorized"},{status:401});const parsed=productSchema.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0].message},{status:400});try{const p=parsed.data,now=new Date(),id=crypto.randomUUID();await getDb().insert(products).values({...p,id,coverImage:p.coverImage||null,variants:JSON.stringify(p.variants),images:JSON.stringify(p.images||[]),createdAt:now,updatedAt:now});return NextResponse.json({id},{status:201})}catch(e){return NextResponse.json({error:String(e).includes("UNIQUE")?"That SKU already exists.":"Could not save product."},{status:400})}}
export async function PUT(req:NextRequest){if(!await getChatGPTUser())return NextResponse.json({error:"Unauthorized"},{status:401});const parsed=productSchema.safeParse(await req.json());if(!parsed.success||!parsed.data.id)return NextResponse.json({error:"Please check all required fields."},{status:400});const p=parsed.data;try{await getDb().update(products).set({...p,coverImage:p.coverImage||null,variants:JSON.stringify(p.variants),images:JSON.stringify(p.images||[]),updatedAt:new Date()}).where(eq(products.id,p.id));return NextResponse.json({ok:true})}catch{return NextResponse.json({error:"Could not update product. The SKU may already exist."},{status:400})}}
export async function DELETE(req:NextRequest){if(!await getChatGPTUser())return NextResponse.json({error:"Unauthorized"},{status:401});const id=req.nextUrl.searchParams.get("id");if(!id)return NextResponse.json({error:"Missing id"},{status:400});await getDb().delete(products).where(eq(products.id,id));return NextResponse.json({ok:true})}
