export type Product = { id:string; name:string; sku:string; category:string; description:string; price:number; moq:number; increment:number; dialColour:string; strapMaterial:string; variants:string[]; stockStatus:"In Stock"|"Out of Stock"; featured:boolean; newArrival:boolean; status:"draft"|"published"; archived:boolean; coverImage?:string; images?:string[] };
export const demoProducts:Product[] = [
{id:"demo-1",name:"Axis Noir Classic",sku:"AT-M101",category:"Men’s Watches",description:"A clean everyday watch with a deep charcoal dial and polished markers.",price:780,moq:6,increment:6,dialColour:"Charcoal",strapMaterial:"PU leather",variants:["Black / Silver","Brown / Rose Gold"],stockStatus:"In Stock",featured:true,newArrival:true,status:"published",archived:false},
{id:"demo-2",name:"Elara Mesh",sku:"AT-W204",category:"Women’s Watches",description:"A slim profile with a refined mesh strap for modern retail collections.",price:690,moq:6,increment:6,dialColour:"Champagne",strapMaterial:"Stainless steel mesh",variants:["Champagne","Silver","Rose Gold"],stockStatus:"In Stock",featured:true,newArrival:false,status:"published",archived:false},
{id:"demo-3",name:"Together Minimal Pair",sku:"AT-C310",category:"Couple Watches",description:"Coordinated minimal dials presented as a matching retail-ready pair.",price:1450,moq:3,increment:3,dialColour:"White",strapMaterial:"Stainless steel",variants:["Silver","Two-tone"],stockStatus:"In Stock",featured:true,newArrival:true,status:"published",archived:false},
{id:"demo-4",name:"Nova Chrono",sku:"AT-M118",category:"Men’s Watches",description:"A bold chronograph-inspired dial with a comfortable stitched strap.",price:920,moq:6,increment:6,dialColour:"Coffee brown",strapMaterial:"PU leather",variants:["Brown","Black"],stockStatus:"Out of Stock",featured:false,newArrival:true,status:"published",archived:false},
{id:"demo-5",name:"Luna Petite",sku:"AT-W221",category:"Women’s Watches",description:"Compact polished case with understated markers and a bracelet strap.",price:740,moq:6,increment:6,dialColour:"Pearl white",strapMaterial:"Alloy bracelet",variants:["Silver","Rose Gold"],stockStatus:"In Stock",featured:false,newArrival:true,status:"published",archived:false},
{id:"demo-6",name:"Urban Steel",sku:"AT-M126",category:"Men’s Watches",description:"A versatile steel bracelet watch with a crisp high-contrast dial.",price:850,moq:12,increment:6,dialColour:"Black",strapMaterial:"Stainless steel",variants:["Silver / Black","Two-tone / White"],stockStatus:"In Stock",featured:false,newArrival:false,status:"published",archived:false}];
export const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
